# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170403_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publikowanyyyy',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publikowany',
            new_name='publikowanyyyy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='utworzony',
            new_name='utworzonyyy',
        ),
    ]
