# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170403_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publikowany',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publikowanyyyy',
            new_name='publikowany',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='utworzonyyy',
            new_name='utworzony',
        ),
    ]
